# This workflow tests all the published solutions

name: Test Solutions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check with pyflakes
        run: for i in */day_*;do echo $i; cd $i; pyflakes *.py ; cd -;done
      - name: Run Tests
        run: for i in */day_*;do echo $i; cd $i; pytest -m "not slow"; cd -;done
